### ISSUE TITLE
Submenus don't move with main menu

### ISSUE THREAD

**Issue by LiteracyFanatic** [phillbush/xmenu#1] opened 2020-05-19 11:48 UTC
If you use the `-w` flag with the example script it becomes possible to move the main menu. Hovering to open the submenu will cause it to spawn in the original location.  I'm using i3 as my window manager.

![1589888574](https://user-images.githubusercontent.com/18249574/82322454-2866e000-999c-11ea-8d41-7642f7a5494a.png)

**Comment by phillbush** [comment] 2020-05-19 13:05
I programmed the `-w` option to emulate the behavior of the menus from the [WindowMaker](https://www.windowmaker.org) window manager.  
As you can see in this gif, the menus in WindowMaker can move freely away from its parent or child menu.

![output](https://user-images.githubusercontent.com/63266536/82329610-19e6eb80-99d1-11ea-9513-44506fbac8fc.gif)

So it is kinda like a feature, not a bug.

But I am planning more command line flags and one of them will move the windows together.

**Comment by phillbush** [comment] 2020-05-19 16:47
Just fixed with the last commit.

**Closed** 2020-05-19 16:48 UTC
Labels: bug

**Comment by phillbush** [comment] 2020-05-19 16:53
I fixed the problem in the last commit.
Note, however, that the `-w` flag can be buggy in tiling window managers.

Tiling window managers resize and move windows at will for they can be tiled. A tiled window manager could try to tile the menus when in window mode (`-w`).l I have to give the window manager hints that the menus are not supposed to be tiled, but the tiling window manager normally ignore windows hints.

**Comment by LiteracyFanatic** [comment] 2020-05-19 20:46
Interesting. I'm not familiar with WindowMaker. Guess I have something new to play around with now.

i3 leaves floating windows alone by default as long as the proper hints are set. With the latest commit, the submenu is spawning in a random location near the top left of the screen away from the main menu. I also tested using openbox and got similar behavior with the difference being that the main menu did not spawn at the location of the mouse. What window manager are you using? I'd like to see if it functions properly for me there so I can figure out whether it's a window manger issue or something else related to my setup.

**Comment by LiteracyFanatic** [comment] 2020-05-19 20:52
![test](https://user-images.githubusercontent.com/18249574/82377087-c2547a00-99e8-11ea-9e19-e82f0c5532b6.png)
