### ISSUE TITLE
cannot launch qutebrowser from xmenu

### ISSUE THREAD

**Issue by pnotz17** [phillbush/xmenu#22] opened 2020-12-31 17:10 UTC
here is my xmenu.sh i dont know if this is xmenu related or through qutebrowser but it works through dmenu
#!/bin/sh

```
cat <<EOF | xmenu -r | sh &
File manager	pcmanfm
Terminal 	st
Web browser	firefox	
Accessories
	feh	feh  ~/Pictures/Wallpapers/*
	vim	st -e vim
Development
	geany	geany
	keepassxc	keepassxc
Graphics
	gimp	gimp
	xsane-scanning	xsane
Network 
	qutebrowser	 /usr/bin/qutebrowser 
	firefox	firefox
	transmission	transmission-gtk
	thunderbird	thunderbird
Multimedia
	alsa mixer	st -e alsamixer
	mpv	mpv
Office
Settings 
	Customize Look & Feel	lxappearance
System 
	htop	st -e htop
Kill	xkill

Leave
	Reboot			reboot
	Shutdown		poweroff
EOF

```

**Comment by phillbush** [comment] 2021-01-01 00:45
xmenu doesn't launch anything, it just prints what the user selects to the stdout.  If you pipe its output into `sh(1)`, the shell will cope with the launching.

If you replace your `xmenu.sh` with the following command, does qutebrowser launches when running it?

```shell
echo qutebrowser | sh
```

**Comment by pnotz17** [comment] 2021-01-01 13:37
no it still doesnt i mean it seems likeits reading something then fails, its only with qutebrowser i dont know why i have been going at this for a week now i have installed re installed x menu ,deleted the binary debuged qutebrowser , it only launches from dmenu

**Comment by phillbush** [comment] 2021-01-01 14:49
If you call `xmenu.sh` from a terminal, rather than from `xclickroot(1)`, the problem persists?

**Comment by pnotz17** [comment] 2021-01-01 15:17
xclickroot is in my .xprofile its always running

**Comment by pnotz17** [comment] 2021-01-01 15:18
hold on il test that actually

**Comment by pnotz17** [comment] 2021-01-01 15:20
that launched it

this is in my .xprofile 
# Autostart
xrandr --output VGA1 --scale 1.25x1.25 &
picom -b &
~/.fehbg &
xset dpms 600 900 1200
xset r rate 350 60
/home/usewr/dwm/dwmbartext.sh &
xclickroot -r /home/panos21/xmenu/xmenu.sh &


# Keymap
#!/bin/sh
setxkbmap "us,gr" -option "grp:alt_shift_toggle"

# Custom Resolution
##!/bin/sh
 xrandr --newmode "1408x792_60.00"   90.75  1408 1480 1624 1840  792 795 800 823 -hsync +vsync
 xrandr --addmode VGA1 1408x792_60.00

#dwm restart loop
#while true; do
    #/usr/local/bin/dwm 2> /dev/null
#done

**Comment by pnotz17** [comment] 2021-01-01 15:37
even if i switch xclickroot to start first in xprofile it doesnt make a diff ,running ./xmenu.sh from term launches quteb that way, i dont get it

**Comment by phillbush** [comment] 2021-01-01 19:09
So the problem is in the environment.  
Your `.xprofile` (or other file such as `.xinitrc` or whatever other file your window manager or display manager sources) seems to set an environment variable or call a program that set things up for qutebrowser. That's why calling `xmenu.sh` earlier doesn't launch qutebrowser (the environment hasn't set up for qutebrowser yet), but calling `xmenu.sh` on a terminal launches it (the environment is already set up).

You need to look for shell scripts your window manager, desktop environment and/or display manager sources.  
What display manager and window manager/desktop environment do you use?  
Look on the Arch Linux wiki for the files those program sources.

**Comment by pnotz17** [comment] 2021-01-01 19:14
i am on arch wm dwm xmonad qtile

**Comment by phillbush** [comment] 2021-01-01 21:20
On your `.xmenu.sh` file, replace the line calling xmenu with the following line and then, after logging up, try to open qutebrowser from xmenu.

```shell
cat <<EOF | xmenu -r | sh >$HOME/log 2>&1 &
```

This will generate a `log` file on your `$HOME` directory, post the content of it here.

**Comment by pnotz17** [comment] 2021-01-01 21:34
i dont know but its solved i put this to apply enviroment globally in /etc/profile

```
# If user ID is greater than or equal to 1000 & if ~/bin exists and is a directory & if ~/bin is not already in your $PATH
# then export ~/bin to your $PATH.
if [[ $UID -ge 1000 && -d $HOME/bin && -z $(echo $PATH | grep -o $HOME/bin) ]]
then
    export PATH="${PATH}:$HOME/bin"
fi

```

**Comment by pnotz17** [comment] 2021-01-01 21:37
```
[359808:359808:0101/233555.435442:FATAL:credentials.cc(302)] : No child processes (10)
sh: line 1: 359808 Trace/breakpoint trap   (core dumped) qutebrowser

```

**Comment by phillbush** [comment] 2021-01-02 01:08
I have no idea why qutebrowser cannot be launched from a script that is ran earlier in the log in process.

I think you should open an issue on [qutebrowser's repo](https://github.com/qutebrowser/qutebrowser) with the title “*qutebrowser does not run when launched from script executed at user log in*” and link this thread there, explaining that you run a script in your `~/.xprofile` (which is sourced by your display manager right after you log in) and that this script launches qutebrowser by printing `qutebrowser` into `sh` standard input when you click on its option on the menu. Also remember to post the content of `log`.

Since this does not seem to be a problem related to xmenu, I'm closing this issue.

**Closed by phillbush** 2021-01-02 01:08 UTC

**Comment by pnotz17** [comment] 2021-01-02 04:34
thank you
